#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use App\MeetLog;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Logger\ConsoleLogger;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;

(new SingleCommandApplication())
    ->setName('Google Meet Log Sync') // Optional
    ->setDescription('Extract log from google meet')
    ->addArgument('date', InputArgument::OPTIONAL, 'Date of the Meets')
    ->addOption('meet', '-m', InputOption::VALUE_OPTIONAL, 'Get only a specific Meet')
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $logger = new ConsoleLogger($output);

        $date = $input->getArgument('date');
        $code = $input->getOption('meet');

        try {
            $meet = new MeetLog($logger);
            $meet->getMeets($date, $code);
        } catch (Exception $e) {
            $logger->error($e->getMessage());
            return Command::FAILURE;
        }
        return Command::SUCCESS;
    })
    ->run();